# Generated by Django 6.0.5 on 2026-06-14 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
