# Generated by Django 6.0.5 on 2026-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
